# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
  binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
- format: binary
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you 
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

dockers:
  - image_templates:
    - "ghcr.io/cryptvault-cloud/vault-cli:{{ .Version }}-amd64"
    - "ghcr.io/cryptvault-cloud/vault-cli:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    goarch: amd64
  - image_templates:
    - "ghcr.io/cryptvault-cloud/vault-cli:{{ .Version }}-arm64"
    - "ghcr.io/cryptvault-cloud/vault-cli:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64
docker_manifests:
  - name_template: "ghcr.io/cryptvault-cloud/vault-cli:{{ .Version }}"
    image_templates:
      - "ghcr.io/cryptvault-cloud/vault-cli:{{ .Version }}-amd64"
      - "ghcr.io/cryptvault-cloud/vault-cli:{{ .Version }}-arm64"
  - name_template: "ghcr.iocryptvault-cloud/vault-cli:latest"
    image_templates:
      - "ghcr.io/cryptvault-cloud/vault-cli:latest-amd64"
      - "ghcr.io/cryptvault-cloud/vault-cli:latest-arm64"

release:
changelog:
  skip: true
